/* Freestanding <inttypes.h>: fixed-width typedefs come from gcc's
   freestanding <stdint.h>; the PRI* macros below are the LP64 set
   (x86-64: int=32 bit, long/pointer=64 bit), which is what mGBA's
   "%" PRIi32 / PRIXPTR uses expand to. */
#ifndef LUAGB_INTTYPES_H
#define LUAGB_INTTYPES_H
#include <stdint.h>

#define PRId8   "d"
#define PRId16  "d"
#define PRId32  "d"
#define PRId64  "ld"
#define PRIdLEAST8  "d"
#define PRIdLEAST16 "d"
#define PRIdLEAST32 "d"
#define PRIdLEAST64 "ld"
#define PRIdFAST8   "d"
#define PRIdFAST16  "ld"
#define PRIdFAST32  "ld"
#define PRIdFAST64  "ld"
#define PRIdMAX "ld"
#define PRIdPTR "ld"

#define PRIi8   "i"
#define PRIi16  "i"
#define PRIi32  "i"
#define PRIi64  "li"
#define PRIiLEAST8  "i"
#define PRIiLEAST16 "i"
#define PRIiLEAST32 "i"
#define PRIiLEAST64 "li"
#define PRIiFAST8   "i"
#define PRIiFAST16  "li"
#define PRIiFAST32  "li"
#define PRIiFAST64  "li"
#define PRIiMAX "li"
#define PRIiPTR "li"

#define PRIu8   "u"
#define PRIu16  "u"
#define PRIu32  "u"
#define PRIu64  "lu"
#define PRIuLEAST8  "u"
#define PRIuLEAST16 "u"
#define PRIuLEAST32 "u"
#define PRIuLEAST64 "lu"
#define PRIuFAST8   "u"
#define PRIuFAST16  "lu"
#define PRIuFAST32  "lu"
#define PRIuFAST64  "lu"
#define PRIuMAX "lu"
#define PRIuPTR "lu"

#define PRIx8   "x"
#define PRIx16  "x"
#define PRIx32  "x"
#define PRIx64  "lx"
#define PRIxLEAST8  "x"
#define PRIxLEAST16 "x"
#define PRIxLEAST32 "x"
#define PRIxLEAST64 "lx"
#define PRIxFAST8   "x"
#define PRIxFAST16  "lx"
#define PRIxFAST32  "lx"
#define PRIxFAST64  "lx"
#define PRIxMAX "lx"
#define PRIxPTR "lx"

#define PRIX8   "X"
#define PRIX16  "X"
#define PRIX32  "X"
#define PRIX64  "lX"
#define PRIXLEAST8  "X"
#define PRIXLEAST16 "X"
#define PRIXLEAST32 "X"
#define PRIXLEAST64 "lX"
#define PRIXFAST8   "X"
#define PRIXFAST16  "lX"
#define PRIXFAST32  "lX"
#define PRIXFAST64  "lX"
#define PRIXMAX "lX"
#define PRIXPTR "lX"

#endif
